name: Build and Publish Java Packages

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: "17"
                  distribution: "temurin"
            - name: Build with Maven
              run: mvn -B package --file pom.xml
    publish:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: "17"
                  distribution: "temurin"
            - name: Publish to GitHub Packages Apache Maven
              run: mvn --batch-mode deploy
              env:
                  GITHUB_TOKEN: ${{ secrets.MAVEN_TOKEN_KEY }}
